[package]
name = "hyperlane_application"
version = "23.0.35"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """Hyperlane application module containing core application logic, controllers, services, and middleware components."""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository = "https://github.com/hyperlane-dev/hyperlane-quick-start.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "data",
    "*.log",
    "*.pid",
    "target",
    ".github",
    ".vscode",
    "node_modules",
    "Cargo.lock",
]

[lib]
path = "lib.rs"

[dependencies]
hyperlane_config = { workspace = true }
hyperlane_plugin = { workspace = true }
hyperlane_resources = { workspace = true }

log = { workspace = true }
md5 = { workspace = true }
rsa = { workspace = true }
uuid = { workspace = true }
redis = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
utoipa = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
chunkify = { workspace = true }
color-log = { workspace = true }
hyperlane = { workspace = true }
once_cell = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
jwt-service = { workspace = true }
urlencoding = { workspace = true }
color-output = { workspace = true }
rust_decimal = { workspace = true }
ed25519-dalek = { workspace = true }
lombok-macros = { workspace = true }
file-operation = { workspace = true }
hyperlane-core = { workspace = true }
server-manager = { workspace = true }
utoipa-rapidoc = { workspace = true }
hyperlane-macros = { workspace = true }
instrument-level = { workspace = true }
bin-encode-decode = { workspace = true }
utoipa-swagger-ui = { workspace = true }
hyperlane-broadcast = { workspace = true }
hyperlane-plugin-websocket = { workspace = true }
