services:
  mysql:
    image: mysql:latest
    container_name: hyperlane_quick_start_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hyperlane
      MYSQL_DATABASE: hyperlane
      MYSQL_USER: hyperlane
      MYSQL_PASSWORD: hyperlane
    expose:
      - '3306'
    volumes:
      - ../../../data/release/mysql_data:/var/lib/mysql
    networks:
      - hyperlane_quick_start_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-phyperlane',
        ]
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  postgresql:
    image: postgres:latest
    container_name: hyperlane_quick_start_postgresql
    restart: always
    environment:
      POSTGRES_DB: hyperlane
      POSTGRES_USER: hyperlane
      POSTGRES_PASSWORD: hyperlane
      POSTGRES_HOST_AUTH_METHOD: md5
    expose:
      - '5432'
    volumes:
      - ../../../data/release/postgres_data:/var/lib/postgresql
    networks:
      - hyperlane_quick_start_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  redis:
    image: redis:latest
    container_name: hyperlane_quick_start_redis
    restart: always
    command: redis-server --requirepass hyperlane
    expose:
      - '6379'
    volumes:
      - ../../../data/release/redis_data:/data
    networks:
      - hyperlane_quick_start_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'hyperlane', 'ping']
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  server:
    build:
      context: ../../../
      dockerfile: ./resources/docker/release/server.dockerfile
    container_name: hyperlane_quick_start_server
    restart: always
    expose:
      - '65002'
    networks:
      - hyperlane_quick_start_network
    depends_on:
      mysql:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  hyperlane_quick_start_network:
    driver: bridge
