/// # mod-visibility-allow: children are addressed by module path from outside this subtree (sibling trees, other crates); a bare `mod` cannot be re-exported to widen it (E0255) and flattening the contents collides on sea-orm's fixed Model/ActiveModel/Entity/Column/Relation names
pub mod auth;
pub mod blog;
pub mod chat;
pub mod cicd;
pub mod dataset;
pub mod diff;
pub mod docs;
pub mod euv;
pub mod euv_docs;
pub mod euv_playground;
pub mod favicon;
pub mod github_pages;
pub mod gomoku;
pub mod ide;
pub mod json;
pub mod monitor;
pub mod notification;
pub mod openapi;
pub mod order;
pub mod qrcode;
pub mod redis;
pub mod rss;
pub mod shortlink;
pub mod static_resource;
pub mod trace;
pub mod tracking;
pub mod upload;
pub mod user;

use super::*;
