pub const DEFAULT_CAPTURE_DURATION: u64 = 60;
pub const MAX_CAPTURE_DURATION: u64 = 3600;
pub const DEFAULT_PACKET_BUFFER_SIZE: usize = 1000;
pub const MAX_CONNECTIONS_DISPLAY: usize = 50;
pub const CAPTURE_INTERVAL_SECONDS: u64 = 2;
pub const NETWORK_STATS_CACHE_TTL: u64 = 30;
