services:
  mysql:
    image: mysql:latest
    container_name: dev_hyperlane_quick_start_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hyperlane
      MYSQL_DATABASE: hyperlane
      MYSQL_USER: hyperlane
      MYSQL_PASSWORD: hyperlane
    ports:
      - '3306:3306'
    volumes:
      - ../../../data/dev/mysql:/var/lib/mysql
    networks:
      - dev_hyperlane_quick_start_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-phyperlane',
        ]
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  postgresql:
    image: postgres:latest
    container_name: dev_hyperlane_quick_start_postgresql
    restart: always
    environment:
      POSTGRES_DB: hyperlane
      POSTGRES_USER: hyperlane
      POSTGRES_PASSWORD: hyperlane
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5432:5432'
    volumes:
      - ../../../data/dev/postgres:/var/lib/postgresql
    networks:
      - dev_hyperlane_quick_start_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  redis:
    image: redis:latest
    container_name: dev_hyperlane_quick_start_redis
    restart: always
    command: redis-server --requirepass hyperlane
    ports:
      - '6379:6379'
    volumes:
      - ../../../data/dev/redis:/data
    networks:
      - dev_hyperlane_quick_start_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'hyperlane', 'ping']
      interval: 6s
      timeout: 1s
      retries: 6
      start_period: 6s

  server:
    build:
      context: ../../../
      dockerfile: ./resources/docker/dev/server.dockerfile
    container_name: dev_hyperlane_quick_start_server
    restart: always
    ports:
      - '80:80'
    environment:
      DOCKER_COMPOSE_FILE_PATH: ${DOCKER_COMPOSE_FILE_PATH}
      DB_CONNECTION_TIMEOUT_MILLIS: ${DB_CONNECTION_TIMEOUT_MILLIS}
      DB_RETRY_INTERVAL_MILLIS: ${DB_RETRY_INTERVAL_MILLIS}
      GPT_API_URL: ${GPT_API_URL}
      GPT_API_KEY: ${GPT_API_KEY}
      GPT_MODEL: ${GPT_MODEL}
      GPT_ENABLE_THINKING: ${GPT_ENABLE_THINKING}
      MYSQL: ${MYSQL}
      POSTGRESQL: ${POSTGRESQL}
      REDIS: ${REDIS}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_BUFFER: ${SERVER_BUFFER}
      SERVER_LOG_SIZE: ${SERVER_LOG_SIZE}
      SERVER_LOG_DIR: ${SERVER_LOG_DIR}
      SERVER_INNER_PRINT: ${SERVER_INNER_PRINT}
      SERVER_INNER_LOG: ${SERVER_INNER_LOG}
      SERVER_NODELAY: ${SERVER_NODELAY}
      SERVER_TTI: ${SERVER_TTI}
      SERVER_PID_FILE_PATH: ${SERVER_PID_FILE_PATH}
      SERVER_REQUEST_HTTP_READ_TIMEOUT_MS: ${SERVER_REQUEST_HTTP_READ_TIMEOUT_MS}
      SERVER_REQUEST_MAX_BODY_SIZE: ${SERVER_REQUEST_MAX_BODY_SIZE}
    networks:
      - dev_hyperlane_quick_start_network
    depends_on:
      mysql:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  dev_hyperlane_quick_start_network:
    external: true
    driver: bridge
