[package]
name = "hyperlane_plugin"
version = "23.0.36"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A powerful and extensible plugin system for the hyperlane framework, providing modularity and customization capabilities."""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository = "https://github.com/hyperlane-dev/hyperlane-quick-start.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "data",
    "*.log",
    "*.pid",
    "target",
    ".github",
    ".vscode",
    "node_modules",
    "Cargo.lock",
]

[lib]
path = "lib.rs"

[dependencies]
hyperlane_resources = { workspace = true }

log = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
color-log = { workspace = true }
hyperlane = { workspace = true }
serde_yaml = { workspace = true }
color-output = { workspace = true }
lombok-macros = { workspace = true }
file-operation = { workspace = true }
hyperlane-core = { workspace = true }
server-manager = { workspace = true }
hyperlane-macros = { workspace = true }
instrument-level = { workspace = true }
