use super::*;

#[derive(utoipa::OpenApi)]
#[openapi(
    components(schemas(
        FileChunkData,
        UploadResponse,
        WebSocketReqData,
        WebSocketRespData,
        OnlineUser,
        UserListResponse,
        ServerStatus,
        SystemInfo,
        NetworkPacket,
        NetworkStats,
        ConnectionInfo,
        NetworkCaptureRequest,
        NetworkCaptureResponse,
    )),
    info(
        title = "Hyperlane",
        version = "latest",
        description = "A lightweight, high-performance, and cross-platform Rust HTTP server library built on Tokio. It simplifies modern web service development by providing built-in support for middleware, WebSocket, Server-Sent Events (SSE), and raw TCP communication. With a unified and ergonomic API across Windows, Linux, and MacOS, it enables developers to build robust, scalable, and event-driven network applications with minimal overhead and maximum flexibility."
    ),
    paths(
        view::favicon::handle,
        controller::chat::html,
        controller::chat::online_users,
        controller::chat::handle,
        controller::hello::handle,
        controller::log::info,
        controller::log::warn,
        controller::log::error,
        controller::monitor::status_sse,
        controller::monitor::system_info,
        controller::monitor::monitor_dashboard,
        controller::monitor::network_capture_data,
        controller::monitor::network_capture_stream,
        controller::mysql::list_records,
        controller::mysql::create_record,
        controller::mysql::update_record,
        controller::mysql::delete_record,
        controller::openapi::json,
        controller::openapi::html,
        controller::postgresql::list_records,
        controller::postgresql::create_record,
        controller::postgresql::update_record,
        controller::postgresql::delete_record,
        controller::redis::list_records,
        controller::redis::create_record,
        controller::redis::update_record,
        controller::redis::delete_record,
        controller::sse::handle,
        controller::upload::static_file,
        controller::upload::html,
        controller::upload::register,
        controller::upload::merge,
        controller::upload::save,
        controller::websocket::handle,
    )
)]
pub struct ApiDoc;
