CREATE TABLE IF NOT EXISTS tracking_record (
    id BIGSERIAL PRIMARY KEY,
    headers TEXT NOT NULL,
    body TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);