#[derive(Debug, Clone, Default)]
pub struct EnvConfig {
    pub gpt_api_url: String,
    pub enable_mysql: bool,
    pub enable_redis: bool,
    pub enable_postgresql: bool,
    pub gtp_model: String,
    pub mysql_host: String,
    pub mysql_port: usize,
    pub mysql_database: String,
    pub mysql_username: String,
    pub mysql_password: String,
    pub redis_host: String,
    pub redis_port: usize,
    pub redis_username: String,
    pub redis_password: String,
    pub postgresql_host: String,
    pub postgresql_port: usize,
    pub postgresql_database: String,
    pub postgresql_username: String,
    pub postgresql_password: String,
}
